import 'antd/lib/alert/style/css';
import 'antd/lib/button/style/css';
import 'antd/lib/col/style/css';
import 'antd/lib/date-picker/style/css';
import 'antd/lib/icon/style/css';
import 'antd/lib/input/style/css';
import 'antd/lib/layout/style/css';
import 'antd/lib/menu/style/css';
import 'antd/lib/popover/style/css';
import 'antd/lib/row/style/css';
import 'antd/lib/select/style/css';
import 'antd/lib/spin/style/css';
import 'antd/lib/table/style/css';
import 'antd/lib/form/style/css';
import 'antd/lib/checkbox/style/css';
import 'antd/lib/card/style/css';
import 'antd/lib/list/style/css';
import 'antd/lib/descriptions/style/css';
import 'antd/lib/avatar/style/css';
import 'antd/lib/timeline/style/css';
import 'antd/lib/result/style/css';
import 'antd/lib/divider/style/css';
import 'antd/lib/popover/style/css';
import 'antd/lib/badge/style/css';
import 'antd/lib/popconfirm/style/css';
import 'antd/lib/message/style/css';
import 'antd/lib/carousel/style/css';
import 'antd/lib/tag/style/css';
import 'antd/lib/comment/style/css';

import * as React from 'react';
import * as ReactDOM from 'react-dom';
import './css/index.css';
import { App } from './views/app';

ReactDOM.render(<App />, document.getElementById('app'));
